@port=3001

### 获得所有cats
GET http://localhost:{{port}}/cats HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJzdWIiOjEsImlhdCI6MTY5NzUxMTYzMiwiZXhwIjoxNjk3NTk4MDMyfQ._LCnl4RpiAvDABfkFgPQjfLG4fEt0V1S0I8TwwCdwnM

### 添加cat
POST http://localhost:{{port}}/cats HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJzdWIiOjEsImlhdCI6MTY5NzUxMTYzMiwiZXhwIjoxNjk3NTk4MDMyfQ._LCnl4RpiAvDABfkFgPQjfLG4fEt0V1S0I8TwwCdwnM

{
    "name": "cat2",
    "age": 2,
    "breed": "breed2"
}

### 错误的参数添加cat
POST http://localhost:{{port}}/cats HTTP/1.1
content-type: application/json

{
    "age": 1,
    "breed": "breed1"
}

### 删除cat
DELETE http://localhost:{{port}}/cats/652c992b0fc6a2c1a86338a7 HTTP/1.1

### 以数字id删除cat
DELETE http://localhost:{{port}}/cats/123 HTTP/1.1

### 删除所有cat
DELETE http://localhost:{{port}}/cats HTTP/1.1
