@port=3001

### 获得所有cats
GET http://localhost:{{port}}/cats

### 添加cat
POST http://localhost:{{port}}/cats HTTP/1.1
content-type: application/json

{
    "name": "cat2",
    "age": 2,
    "breed": "breed2"
}

### 错误的参数添加cat
POST http://localhost:{{port}}/cats HTTP/1.1
content-type: application/json

{
    "age": 1,
    "breed": "breed1"
}

### 删除cat
DELETE http://localhost:{{port}}/cats/652c9ca0d3536b9a634d0012

### 以数字id删除cat
DELETE http://localhost:{{port}}/cats/123

### 删除所有cat
DELETE http://localhost:{{port}}/cats
