@port=3001

### auth/login ok
POST http://localhost:{{port}}/auth/login HTTP/1.1
content-type: application/json

{
  "username": "john",
  "password": "changeme"
}

### auth/login fail
POST http://localhost:{{port}}/auth/login HTTP/1.1
content-type: application/json

{
  "username": "john",
  "password": "wrongpassword"
}

### GET /profile
GET http://localhost:{{port}}/profile HTTP/1.1

### POST /auth/login
POST http://localhost:{{port}}/auth/login HTTP/1.1
content-type: application/json

{
  "username": "john",
  "password": "changeme"
}

### GET /profile 将上一步中的token放到header中
GET http://localhost:{{port}}/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJzdWIiOjEsImlhdCI6MTY5NzQzMTk3MywiZXhwIjoxNjk3NTE4MzczfQ.Zqo7j31UszELQFySZKErszBGDgPkegsYqy6Sl7vdVwo
