@port=3000

### auth/login ok
POST http://localhost:{{port}}/auth/login HTTP/1.1

### auth/login fail
POST http://localhost:{{port}}/auth/login?code=695ub80022764364b56ce1fed626591e&redirect_uri=http://localhost:{{port}} HTTP/1.1


### auth/login/local ok
POST http://localhost:{{port}}/auth/login/local HTTP/1.1
content-type: application/json

{
  "username": "john",
  "password": "changeme"
}

### auth/login/local fail
POST http://localhost:{{port}}/auth/login/local HTTP/1.1
content-type: application/json

{
  "username": "john",
  "password": "xxxxx"
}

### GET /profile
GET http://localhost:{{port}}/profile HTTP/1.1

### POST /auth/login
POST http://localhost:{{port}}/auth/login HTTP/1.1
content-type: application/json

{
  "username": "john",
  "password": "changeme"
}

### POST /auth/login
POST http://localhost:{{port}}/auth/login HTTP/1.1
content-type: application/json

{
  "username": "admin",
  "password": "admin"
}

### GET /profile 将上一步中的token放到header中
GET http://localhost:{{port}}/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJzdWIiOjEsImlhdCI6MTY5NzUxMTYzMiwiZXhwIjoxNjk3NTk4MDMyfQ._LCnl4RpiAvDABfkFgPQjfLG4fEt0V1S0I8TwwCdwnM
